CREATE TABLE IF NOT EXISTS "reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reviewer_name" text NOT NULL,
	"reviewer_email" text,
	"reviewer_city" text,
	"reviewer_state" text,
	"rating" integer NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"loan_status" text,
	"loan_type" text,
	"interest_rate_experience" text,
	"closed_on_time" boolean,
	"fees_experience" text,
	"loan_term" text,
	"loan_program" text,
	"is_first_time_buyer" boolean,
	"is_self_employed" boolean,
	"status" text DEFAULT 'pending',
	"response_text" text,
	"response_date" timestamp,
	"review_date" date,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
