import { describe, it, expect, vi, beforeEach } from 'vitest'
import { Webhook } from 'svix'

// The webhook: signature, account-wide domain filter, body fetch, store,
// delivery events. The service and AI are mocked; addressing is real.

const storeInboundEmail = vi.fn()
const updateDeliveryStatus = vi.fn()
vi.mock('@/lib/email/admin-inbox', () => ({
  AdminInboxService: {
    storeInboundEmail: (...a: unknown[]) => storeInboundEmail(...a),
    updateDeliveryStatus: (...a: unknown[]) => updateDeliveryStatus(...a),
  },
}))

const receivingGet = vi.fn()
vi.mock('@/lib/email/resend', () => ({
  getResend: () => ({ emails: { receiving: { get: receivingGet } } }),
  isResendConfigured: () => true,
}))

vi.mock('@/lib/ai/ai-email', () => ({
  classifyAndDraftReply: vi.fn(),
  storeClassification: vi.fn(),
  sendAutoReply: vi.fn(),
}))
vi.mock('@/lib/logger', () => ({ logger: { error: vi.fn(), warn: vi.fn(), info: vi.fn(), debug: vi.fn() } }))
vi.mock('next/server', async (importOriginal) => {
  const actual = await importOriginal<typeof import('next/server')>()
  return { ...actual, after: (fn: () => unknown) => { void fn() } }
})

const SECRET = 'whsec_' + Buffer.from('test-secret-test-secret-1234').toString('base64')
const { POST } = await import('./route')

function signed(body: unknown, secret = SECRET) {
  const payload = JSON.stringify(body)
  const ts = Math.floor(Date.now() / 1000)
  const signature = new Webhook(secret).sign('msg_1', new Date(ts * 1000), payload)
  return new Request('https://bocabanker.com/api/email/webhook', {
    method: 'POST',
    body: payload,
    headers: { 'svix-id': 'msg_1', 'svix-timestamp': String(ts), 'svix-signature': signature },
  })
}

beforeEach(() => {
  storeInboundEmail.mockReset()
  updateDeliveryStatus.mockReset()
  receivingGet.mockReset()
  process.env.RESEND_WEBHOOK_SECRET = SECRET
  delete process.env.XAI_API_KEY
  delete process.env.ADMIN_EMAIL_ADDRESS
  delete process.env.RESEND_FROM_EMAIL
})

describe('POST /api/email/webhook', () => {
  it('rejects a missing secret and a bad signature', async () => {
    delete process.env.RESEND_WEBHOOK_SECRET
    const noSecret = await POST(signed({ type: 'email.received', data: {} }) as never)
    expect(noSecret.status).toBe(500)

    process.env.RESEND_WEBHOOK_SECRET = SECRET
    const forged = await POST(signed({ type: 'email.received', data: {} }, 'whsec_' + Buffer.from('other-secret-other-secret-1').toString('base64')) as never)
    expect(forged.status).toBe(401)
    expect(storeInboundEmail).not.toHaveBeenCalled()
  })

  it("drops another project's mail before fetching the body", async () => {
    const res = await POST(signed({ type: 'email.received', data: { email_id: 'e1', from: 'a@b.com', to: ['hello@digis.cc'] } }) as never)
    expect(res.status).toBe(200)
    expect(await res.json()).toMatchObject({ ignored: 'not our domain' })
    expect(receivingGet).not.toHaveBeenCalled()
    expect(storeInboundEmail).not.toHaveBeenCalled()
  })

  it('fetches the body and stores our mail with name, thread tag, cc and attachments', async () => {
    const thread = '0f3c6d2a-1b4e-4c8d-9e7f-0a1b2c3d4e5f'
    receivingGet.mockResolvedValue({
      data: {
        id: 'e1',
        from: 'jose@example.com',
        to: [`team+${thread}@bocabanker.com`],
        cc: ['Pal <pal@example.com>'],
        bcc: null,
        subject: 'Re: Your rate quote',
        text: 'Thanks!',
        html: '<p>Thanks!</p>',
        message_id: '<m2@example.com>',
        headers: { From: '=?UTF-8?B?Sm9zw6k=?= <jose@example.com>', 'In-Reply-To': '<m1@bocabanker.com>', 'Message-ID': '<m2@example.com>' },
        attachments: [{ id: 'att1', filename: 'doc.pdf', content_type: 'application/pdf', size: 1234 }],
      },
      error: null,
    })
    storeInboundEmail.mockResolvedValue({ id: 'row', isSpam: false, threadId: thread, userId: 'u', clientId: null, createdAt: new Date() })

    const res = await POST(signed({ type: 'email.received', data: { email_id: 'e1', from: 'jose@example.com', to: [`team+${thread}@bocabanker.com`] } }) as never)
    expect(res.status).toBe(200)
    expect(await res.json()).toMatchObject({ success: true, stored: true })
    expect(receivingGet).toHaveBeenCalledWith('e1')
    expect(storeInboundEmail).toHaveBeenCalledTimes(1)
    expect(storeInboundEmail.mock.calls[0][0]).toMatchObject({
      from: 'jose@example.com',
      fromName: 'José',
      to: `team+${thread}@bocabanker.com`,
      subject: 'Re: Your rate quote',
      text: 'Thanks!',
      html: '<p>Thanks!</p>',
      messageId: 'm2@example.com',
      inReplyToHeader: '<m1@bocabanker.com>',
      threadIdHint: thread,
      resendEmailId: 'e1',
      cc: ['pal@example.com'],
      attachments: [{ id: 'att1', filename: 'doc.pdf', contentType: 'application/pdf', size: 1234 }],
      autoGenerated: false,
    })
  })

  it('flags auto-responders so they are never classified or answered', async () => {
    receivingGet.mockResolvedValue({
      data: { id: 'e2', from: 'jane@example.com', to: ['team@bocabanker.com'], cc: null, bcc: null, subject: 'Out of office', text: 'Away', html: null, message_id: '<ooo@example.com>', headers: { 'Auto-Submitted': 'auto-replied' }, attachments: [] },
      error: null,
    })
    storeInboundEmail.mockResolvedValue({ id: 'row2', isSpam: false, threadId: 't', userId: 'u', clientId: null, createdAt: new Date() })
    await POST(signed({ type: 'email.received', data: { email_id: 'e2', from: 'jane@example.com', to: ['team@bocabanker.com'] } }) as never)
    expect(storeInboundEmail.mock.calls[0][0]).toMatchObject({ autoGenerated: true })
  })

  it('returns 502 when the body fetch fails so Svix retries', async () => {
    receivingGet.mockResolvedValue({ data: null, error: { message: 'boom' } })
    const res = await POST(signed({ type: 'email.received', data: { email_id: 'e3', from: 'a@b.com', to: ['team@bocabanker.com'] } }) as never)
    expect(res.status).toBe(502)
    expect(storeInboundEmail).not.toHaveBeenCalled()
  })

  it('acknowledges a duplicate delivery', async () => {
    receivingGet.mockResolvedValue({ data: { id: 'e4', from: 'a@b.com', to: ['team@bocabanker.com'], cc: null, bcc: null, subject: 'x', text: 'x', html: null, message_id: '<x@b.com>', headers: {}, attachments: [] }, error: null })
    storeInboundEmail.mockResolvedValue(null)
    const res = await POST(signed({ type: 'email.received', data: { email_id: 'e4', from: 'a@b.com', to: ['team@bocabanker.com'] } }) as never)
    expect(await res.json()).toMatchObject({ success: true, duplicate: true })
  })

  it('maps delivery events onto the outbound row', async () => {
    for (const [type, status] of [['email.delivered', 'delivered'], ['email.bounced', 'bounced'], ['email.failed', 'failed']] as const) {
      const res = await POST(signed({ type, data: { email_id: `re-${status}` } }) as never)
      expect(res.status).toBe(200)
      expect(updateDeliveryStatus).toHaveBeenCalledWith(`re-${status}`, status)
    }
  })
})
