import type { InboxStatus } from '@/lib/email/inbox-status';

export type { InboxStatus };

export type EmailDirection = 'inbound' | 'outbound';
export type EmailStatus = 'received' | 'read' | 'replied' | 'sent' | 'delivered' | 'bounced' | 'failed';
export type InboxFolder = 'inbox' | 'unread' | 'starred' | 'sent' | 'spam';
export type BulkAction = 'markRead' | 'markUnread' | 'star' | 'unstar' | 'spam' | 'notSpam' | 'delete';

export interface AttachmentMeta {
  id: string;
  filename: string;
  contentType?: string;
  size?: number;
}

export interface EmailMetadata {
  messageId?: string;
  headers?: Record<string, string>;
  cc?: string[];
  attachments?: AttachmentMeta[];
  test?: boolean;
  autoGenerated?: boolean;
}

interface ClientFields {
  clientId: string | null;
  clientFirstName: string | null;
  clientLastName: string | null;
  clientEmail: string | null;
}

export interface EmailListItem extends ClientFields {
  id: string;
  direction: EmailDirection;
  status: EmailStatus;
  threadId: string | null;
  fromEmail: string;
  fromName: string | null;
  toEmail: string;
  toName: string | null;
  subject: string;
  /** One-line preview (server-trimmed). */
  bodyText: string | null;
  isRead: boolean | null;
  isSpam: boolean;
  isStarred: boolean;
  template: string | null;
  createdAt: string;
  aiCategory: string | null;
  aiConfidence: number | null;
  aiSummary: string | null;
  isTest?: boolean;
  hasAttachments?: boolean;
}

export interface EmailDetail extends ClientFields {
  id: string;
  direction: EmailDirection;
  status: EmailStatus;
  threadId: string | null;
  inReplyToId: string | null;
  resendId: string | null;
  fromEmail: string;
  fromName: string | null;
  toEmail: string;
  toName: string | null;
  cc: string | null;
  subject: string;
  bodyText: string | null;
  bodyHtml: string | null;
  isRead: boolean | null;
  isSpam: boolean;
  isStarred: boolean;
  template: string | null;
  metadata: EmailMetadata | null;
  createdAt: string;
  readAt: string | null;
  repliedAt: string | null;
  aiCategory: string | null;
  aiConfidence: number | null;
  aiSummary: string | null;
  aiDraftText: string | null;
  aiDraftHtml: string | null;
  aiProcessedAt: string | null;
}

export interface FolderCounts {
  unread: number;
  starred: number;
  spam: number;
}

export const FOLDERS: ReadonlyArray<{ value: InboxFolder; label: string }> = [
  { value: 'inbox', label: 'Inbox' },
  { value: 'unread', label: 'Unread' },
  { value: 'starred', label: 'Starred' },
  { value: 'sent', label: 'Sent' },
  { value: 'spam', label: 'Spam' },
];

/** Badge palettes on the navy/gold dashboard theme. */
export type BadgeTone = 'navy' | 'gold' | 'neutral' | 'green' | 'red' | 'blue' | 'violet';

export const BADGE_TONES: Record<BadgeTone, string> = {
  navy: 'bg-navy text-white border-navy',
  gold: 'bg-amber-50 text-amber-700 border-amber-200',
  neutral: 'bg-gray-50 text-gray-600 border-gray-200',
  green: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  red: 'bg-red-50 text-red-700 border-red-200',
  blue: 'bg-blue-50 text-blue-700 border-blue-200',
  violet: 'bg-violet-50 text-violet-700 border-violet-200',
};

export const AI_CATEGORY_LABELS: Record<string, { label: string; tone: BadgeTone }> = {
  cost_seg_inquiry: { label: 'Cost seg', tone: 'gold' },
  property_question: { label: 'Property', tone: 'gold' },
  study_request: { label: 'Study request', tone: 'green' },
  mortgage_inquiry: { label: 'Mortgage', tone: 'blue' },
  loan_status: { label: 'Loan status', tone: 'blue' },
  rate_question: { label: 'Rates', tone: 'blue' },
  scheduling: { label: 'Scheduling', tone: 'violet' },
  general_inquiry: { label: 'General', tone: 'neutral' },
  feedback: { label: 'Feedback', tone: 'neutral' },
  partnership: { label: 'Partnership', tone: 'neutral' },
  support: { label: 'Support', tone: 'neutral' },
  personal: { label: 'Personal', tone: 'neutral' },
  legal_compliance: { label: 'Legal', tone: 'red' },
  spam: { label: 'Spam', tone: 'red' },
  other: { label: 'Other', tone: 'neutral' },
};

export const STATUS_LABELS: Record<EmailStatus, { label: string; tone: BadgeTone }> = {
  received: { label: 'New', tone: 'gold' },
  read: { label: 'Read', tone: 'neutral' },
  replied: { label: 'Replied', tone: 'green' },
  sent: { label: 'Sent', tone: 'neutral' },
  delivered: { label: 'Delivered', tone: 'green' },
  bounced: { label: 'Bounced', tone: 'red' },
  failed: { label: 'Failed', tone: 'red' },
};

/** Categories the AI may answer by itself when auto-reply is on. */
export const AUTO_REPLY_CATEGORY_NAMES = [
  'Cost segregation inquiries',
  'Property questions',
  'Study requests',
  'Mortgage inquiries',
  'Loan status questions',
  'Rate questions',
  'Scheduling',
  'General inquiries',
];

export const HELD_CATEGORY_NAMES = [
  'Feedback and complaints',
  'Partnerships and vendor pitches',
  'Support issues',
  'Personal mail, spam and anything unclear',
];

export function readAttachments(metadata: EmailMetadata | null | undefined): AttachmentMeta[] {
  return Array.isArray(metadata?.attachments) ? metadata.attachments : [];
}

export function readCc(email: Pick<EmailDetail, 'metadata' | 'cc'>): string[] {
  if (Array.isArray(email.metadata?.cc) && email.metadata.cc.length > 0) return email.metadata.cc;
  return (email.cc || '').split(',').map((s) => s.trim()).filter(Boolean);
}

export function clientName(e: Pick<ClientFields, 'clientFirstName' | 'clientLastName'>): string | null {
  const name = `${e.clientFirstName || ''} ${e.clientLastName || ''}`.trim();
  return name || null;
}

export function formatBytes(n: number) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

export function formatListDate(dateStr: string) {
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) return '';
  const now = new Date();
  const sameDay = date.toDateString() === now.toDateString();
  if (sameDay) return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  const days = Math.floor((now.getTime() - date.getTime()) / 86_400_000);
  if (days < 7) return date.toLocaleDateString('en-US', { weekday: 'short' });
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', ...(date.getFullYear() !== now.getFullYear() && { year: 'numeric' }) });
}

export function formatFullDate(dateStr: string) {
  const date = new Date(dateStr);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });
}

/** Display name for a counterpart: name if we have one, else the address. */
export function counterpart(e: Pick<EmailListItem, 'direction' | 'fromEmail' | 'fromName' | 'toEmail' | 'toName'>) {
  return e.direction === 'inbound'
    ? { name: e.fromName || e.fromEmail, address: e.fromEmail }
    : { name: e.toName || e.toEmail, address: e.toEmail };
}

/** The quoted block shown (read-only) under a reply; the server quotes the original itself when sending. */
export function quotePreview(email: Pick<EmailDetail, 'bodyText' | 'bodyHtml' | 'fromName' | 'fromEmail' | 'createdAt'>): string | undefined {
  const text = email.bodyText || (email.bodyHtml ? email.bodyHtml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim() : '');
  if (!text) return undefined;
  const clipped = text.length > 2000 ? `${text.slice(0, 2000)}…` : text;
  return `--- On ${new Date(email.createdAt).toLocaleString('en-US')}, ${email.fromName || email.fromEmail} wrote: ---\n${clipped}`;
}
