import { randomUUID } from 'crypto';
import { db } from '@/db';
import { emails, emailLogs, clients, platformSettings } from '@/db/schema';
import { eq, ne, desc, asc, and, or, ilike, count, inArray, sql } from 'drizzle-orm';
import { sendEmail } from './resend';
import { getFromAddress, isValidEmail, threadReplyAddress } from './inbound-address';
import { brandedTemplate, textToHtml, quotedOriginalHtml, quotedOriginalText } from './render';
import { getDefaultOwnerId } from './default-owner';
import { escapeLike } from './ids';
import { logger } from '@/lib/logger';

// The one inbox for Boca Banker. Replies are addressed to a per-thread
// plus-address on the receiving domain (team+<threadId>@bocabanker.com —
// see inbound-address.ts). The routes are admin-only and the platform has a
// single admin, so the service does not scope rows by owner.

// ── Spam filter ──

const SPAM_PATTERNS = [
  /\b(viagra|cialis|casino|lottery|prince|inheritance)\b/i,
  /\b(unsubscribe.*click here|click here now|act now|limited time|free money)\b/i,
  /\b(make money fast|earn extra cash|no obligation|you have been selected|congratulations you won)\b/i,
  /\b(bitcoin.*invest|crypto.*guaranteed|guaranteed return|cryptocurrency opportunity)\b/i,
  /\b(nigerian|wire transfer|western union)\b/i,
];

const SPAM_TLDS = ['.xyz', '.top', '.click', '.bid', '.win', '.loan', '.buzz', '.icu'];

/** Bulk senders nobody answers: filed as spam, still recoverable. */
const SPAM_SENDER_LOCAL_PARTS = /^(newsletter|marketing|promo(tions?)?|offers?|deals?)$/i;

export function isLikelySpam(email: { from: string; subject: string; text?: string | null }): boolean {
  const content = `${email.subject} ${email.text || ''}`;
  const matchCount = SPAM_PATTERNS.filter((p) => p.test(content)).length;
  const [local = '', fromDomain = ''] = email.from.toLowerCase().split('@');
  const isSpamTLD = SPAM_TLDS.some((tld) => fromDomain.endsWith(tld));
  return matchCount >= 2 || isSpamTLD || SPAM_SENDER_LOCAL_PARTS.test(local);
}

// ── Metadata (JSON in emails.metadata) ──

export interface EmailAttachmentMeta {
  id: string;
  filename: string;
  contentType: string;
  size?: number;
}

export interface EmailMetadata {
  /** RFC Message-ID of an inbound email (bare, no angle brackets). */
  messageId?: string;
  /** Threading headers we sent (In-Reply-To / References). */
  headers?: Record<string, string>;
  cc?: string[];
  attachments?: EmailAttachmentMeta[];
  /** Set on the "Send me a test" row so the UI can label it. */
  test?: boolean;
  /** Auto-responder / list mail — never classified or auto-replied. */
  autoGenerated?: boolean;
  /** Legacy flag from before the is_spam column. */
  spamFiltered?: boolean;
}

export function readMetadata(raw: unknown): EmailMetadata {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return {};
  return raw as EmailMetadata;
}

// ── Folders ──

export const INBOX_FOLDERS = ['inbox', 'unread', 'starred', 'sent', 'spam'] as const;
export type InboxFolder = (typeof INBOX_FOLDERS)[number];

export function isInboxFolder(v: unknown): v is InboxFolder {
  return typeof v === 'string' && (INBOX_FOLDERS as readonly string[]).includes(v);
}

function folderCondition(folder: InboxFolder) {
  switch (folder) {
    case 'inbox':
      return and(eq(emails.direction, 'inbound'), eq(emails.isSpam, false));
    case 'unread':
      return and(eq(emails.direction, 'inbound'), eq(emails.isSpam, false), eq(emails.isRead, false));
    case 'starred':
      return and(eq(emails.isStarred, true), eq(emails.isSpam, false));
    case 'sent':
      return eq(emails.direction, 'outbound');
    case 'spam':
      return eq(emails.isSpam, true);
  }
}

export const BULK_ACTIONS = ['markRead', 'markUnread', 'star', 'unstar', 'spam', 'notSpam', 'delete'] as const;
export type BulkAction = (typeof BULK_ACTIONS)[number];

export function isBulkAction(v: unknown): v is BulkAction {
  return typeof v === 'string' && (BULK_ACTIONS as readonly string[]).includes(v);
}

/** Only keys the inbox UI may read or write through /api/email/inbox/settings. */
export const INBOX_SETTING_KEYS = ['ai_auto_reply_enabled'] as const;
export type InboxSettingKey = (typeof INBOX_SETTING_KEYS)[number];

export function isInboxSettingKey(v: unknown): v is InboxSettingKey {
  return typeof v === 'string' && (INBOX_SETTING_KEYS as readonly string[]).includes(v);
}

/** A thread is `thread_id`, or the root email's own id for legacy rows stored before thread ids existed. */
function inThread(threadId: string) {
  return or(eq(emails.id, threadId), eq(emails.threadId, threadId))!;
}

const CLIENT_COLUMNS = {
  clientFirstName: clients.firstName,
  clientLastName: clients.lastName,
  clientEmail: clients.email,
};

const LIST_COLUMNS = {
  id: emails.id,
  direction: emails.direction,
  status: emails.status,
  threadId: emails.threadId,
  fromEmail: emails.fromEmail,
  fromName: emails.fromName,
  toEmail: emails.toEmail,
  toName: emails.toName,
  subject: emails.subject,
  bodyText: emails.bodyText,
  bodyHtml: emails.bodyHtml,
  isRead: emails.isRead,
  isSpam: emails.isSpam,
  isStarred: emails.isStarred,
  clientId: emails.clientId,
  template: emails.template,
  metadata: emails.metadata,
  createdAt: emails.createdAt,
  aiCategory: emails.aiCategory,
  aiConfidence: emails.aiConfidence,
  aiSummary: emails.aiSummary,
  ...CLIENT_COLUMNS,
};

const DETAIL_COLUMNS = {
  id: emails.id,
  direction: emails.direction,
  status: emails.status,
  threadId: emails.threadId,
  inReplyToId: emails.inReplyToId,
  resendId: emails.resendId,
  fromEmail: emails.fromEmail,
  fromName: emails.fromName,
  toEmail: emails.toEmail,
  toName: emails.toName,
  cc: emails.cc,
  subject: emails.subject,
  bodyText: emails.bodyText,
  bodyHtml: emails.bodyHtml,
  isRead: emails.isRead,
  isSpam: emails.isSpam,
  isStarred: emails.isStarred,
  clientId: emails.clientId,
  template: emails.template,
  metadata: emails.metadata,
  createdAt: emails.createdAt,
  readAt: emails.readAt,
  repliedAt: emails.repliedAt,
  aiCategory: emails.aiCategory,
  aiConfidence: emails.aiConfidence,
  aiSummary: emails.aiSummary,
  aiDraftText: emails.aiDraftText,
  aiDraftHtml: emails.aiDraftHtml,
  aiProcessedAt: emails.aiProcessedAt,
  ...CLIENT_COLUMNS,
};

export type InboxEmailDetail = Awaited<ReturnType<typeof AdminInboxService.getEmail>>;

/** One-line preview for the list: plain text, else text stripped from the HTML. */
function preview(bodyText: string | null, bodyHtml: string | null): string | null {
  const text = bodyText || (bodyHtml ? bodyHtml.replace(/<(style|script|head)[^>]*>[\s\S]*?<\/\1>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;/gi, ' ') : '');
  const clean = text.replace(/\s+/g, ' ').trim();
  return clean ? clean.slice(0, 160) : null;
}

// ── Service ──

export const AdminInboxService = {
  async listEmails({
    folder = 'inbox',
    search,
    page = 1,
    limit = 25,
  }: {
    folder?: InboxFolder;
    search?: string;
    page?: number;
    limit?: number;
  }) {
    const conditions = [folderCondition(folder)];

    const q = (search || '').trim();
    if (q) {
      const like = `%${escapeLike(q)}%`;
      conditions.push(
        or(
          ilike(emails.subject, like),
          ilike(emails.fromEmail, like),
          ilike(emails.fromName, like),
          ilike(emails.toEmail, like),
          ilike(emails.bodyText, like),
          ilike(clients.firstName, like),
          ilike(clients.lastName, like),
        )!,
      );
    }

    const where = and(...conditions);

    const [rows, [countResult]] = await Promise.all([
      db
        .select(LIST_COLUMNS)
        .from(emails)
        .leftJoin(clients, eq(emails.clientId, clients.id))
        .where(where)
        .orderBy(desc(emails.createdAt))
        .limit(limit)
        .offset((page - 1) * limit),
      db
        .select({ value: count() })
        .from(emails)
        .leftJoin(clients, eq(emails.clientId, clients.id))
        .where(where),
    ]);

    // The list needs a one-line preview, not whole bodies.
    const list = rows.map(({ bodyText, bodyHtml, metadata, ...r }) => ({
      ...r,
      bodyText: preview(bodyText, bodyHtml),
      isTest: readMetadata(metadata).test === true,
      hasAttachments: (readMetadata(metadata).attachments?.length ?? 0) > 0,
    }));

    const total = countResult?.value ?? 0;
    return { emails: list, total, page, limit, totalPages: Math.max(1, Math.ceil(total / limit)) };
  },

  /** Badge numbers for the folder pills, in one query. */
  async getFolderCounts() {
    const [row] = await db
      .select({
        unread: sql<number>`count(*) filter (where ${emails.direction} = 'inbound' and ${emails.isRead} = false and ${emails.isSpam} = false)`.mapWith(Number),
        starred: sql<number>`count(*) filter (where ${emails.isStarred} = true and ${emails.isSpam} = false)`.mapWith(Number),
        spam: sql<number>`count(*) filter (where ${emails.isSpam} = true)`.mapWith(Number),
      })
      .from(emails);
    return { unread: row?.unread ?? 0, starred: row?.starred ?? 0, spam: row?.spam ?? 0 };
  },

  async getEmail(id: string) {
    const [email] = await db
      .select(DETAIL_COLUMNS)
      .from(emails)
      .leftJoin(clients, eq(emails.clientId, clients.id))
      .where(eq(emails.id, id))
      .limit(1);
    return email || null;
  },

  async getThread(threadId: string) {
    return db
      .select(DETAIL_COLUMNS)
      .from(emails)
      .leftJoin(clients, eq(emails.clientId, clients.id))
      .where(inThread(threadId))
      .orderBy(asc(emails.createdAt))
      // Bound pathological threads
      .limit(100);
  },

  async markRead(id: string, isRead: boolean) {
    await this.bulk(isRead ? 'markRead' : 'markUnread', [id]);
  },

  async setStar(id: string, isStarred: boolean) {
    await this.bulk(isStarred ? 'star' : 'unstar', [id]);
  },

  async markSpam(id: string, isSpam: boolean) {
    await this.bulk(isSpam ? 'spam' : 'notSpam', [id]);
  },

  async deleteEmail(id: string) {
    await this.bulk('delete', [id]);
  },

  async bulk(action: BulkAction, ids: string[]) {
    if (ids.length === 0) return;
    switch (action) {
      case 'markRead':
        // 'read' only replaces the initial 'received'; never clobber 'replied'.
        await db
          .update(emails)
          .set({
            isRead: true,
            readAt: new Date(),
            status: sql`CASE WHEN ${emails.status} = 'received' THEN 'read' ELSE ${emails.status} END`,
          })
          .where(inArray(emails.id, ids));
        return;
      case 'markUnread':
        await db
          .update(emails)
          .set({
            isRead: false,
            readAt: null,
            status: sql`CASE WHEN ${emails.status} = 'read' THEN 'received' ELSE ${emails.status} END`,
          })
          .where(and(inArray(emails.id, ids), eq(emails.direction, 'inbound')));
        return;
      case 'star':
        await db.update(emails).set({ isStarred: true }).where(inArray(emails.id, ids));
        return;
      case 'unstar':
        await db.update(emails).set({ isStarred: false }).where(inArray(emails.id, ids));
        return;
      case 'spam':
        await db.update(emails).set({ isSpam: true }).where(inArray(emails.id, ids));
        return;
      case 'notSpam':
        await db.update(emails).set({ isSpam: false }).where(inArray(emails.id, ids));
        return;
      case 'delete':
        // Clear references first so no row points at a deleted one — inside
        // a transaction so references are never cleared without the delete.
        await db.transaction(async (tx) => {
          await tx.update(emails).set({ threadId: null }).where(inArray(emails.threadId, ids));
          await tx.update(emails).set({ inReplyToId: null }).where(inArray(emails.inReplyToId, ids));
          await tx.delete(emails).where(inArray(emails.id, ids));
        });
        return;
    }
  },

  async getUnreadCount() {
    const [result] = await db
      .select({ value: count() })
      .from(emails)
      .where(and(eq(emails.direction, 'inbound'), eq(emails.isRead, false), eq(emails.isSpam, false)));
    return result?.value ?? 0;
  },

  /**
   * Compose or reply. The body is plain text from the admin; it is rendered
   * into the branded template and, for a reply, the original is quoted as
   * escaped text. Reply-To is the per-thread plus-address so the answer
   * comes back tagged with this thread, and In-Reply-To/References make the
   * recipient's client group it.
   */
  async sendNewEmail({
    to,
    subject,
    bodyText,
    replyToEmailId,
    userId,
    test = false,
  }: {
    to: string;
    subject: string;
    bodyText: string;
    replyToEmailId?: string | null;
    /** The admin sending it (owner of the outbound row). */
    userId: string | null;
    test?: boolean;
  }) {
    const recipient = to.trim().toLowerCase();
    if (!isValidEmail(recipient)) {
      return { success: false as const, error: 'Enter a valid email address' };
    }
    const cleanSubject = subject.trim();
    if (!cleanSubject) {
      return { success: false as const, error: 'Subject is required' };
    }
    const cleanBody = bodyText.trim();
    if (!cleanBody) {
      return { success: false as const, error: 'Message is required' };
    }

    let threadId: string | null = null;
    let inReplyToId: string | undefined;
    let clientId: string | undefined;
    let inReplyToMessageId: string | null = null;
    let referencesMessageIds: string[] | null = null;
    let quotedHtml = '';
    let quotedText = '';

    if (replyToEmailId) {
      const [original] = await db.select().from(emails).where(eq(emails.id, replyToEmailId)).limit(1);
      if (!original) {
        return { success: false as const, error: 'The email you are replying to no longer exists' };
      }
      threadId = original.threadId || original.id;
      inReplyToId = original.id;
      clientId = original.clientId || undefined;

      const meta = readMetadata(original.metadata);
      if (original.direction === 'inbound' && meta.messageId) {
        // Carry the References chain forward so long threads keep grouping
        // in the recipient's client.
        inReplyToMessageId = meta.messageId;
        const prior = (meta.headers?.References || '').match(/<[^>]+>/g)?.map((s) => s.slice(1, -1)) || [];
        referencesMessageIds = [...prior, meta.messageId];
      }

      quotedHtml = quotedOriginalHtml(original);
      quotedText = quotedOriginalText(original);
    }

    if (!threadId) threadId = randomUUID();

    const html = brandedTemplate(textToHtml(cleanBody), quotedHtml || undefined);
    const text = quotedText ? `${cleanBody}\n\n${quotedText}` : cleanBody;

    const result = await sendEmail({
      to: recipient,
      subject: cleanSubject,
      html,
      text,
      userId,
      clientId,
      template: replyToEmailId ? 'reply' : test ? 'inbox-test' : 'compose',
      threadId,
      inReplyToId,
      inReplyToMessageId,
      referencesMessageIds,
      replyTo: threadReplyAddress(threadId),
      idempotencyKey: `inbox-${randomUUID()}`,
      metadata: test ? { test: true } : undefined,
    });

    if (!result.success) {
      return { success: false as const, error: result.error || 'Failed to send' };
    }

    if (replyToEmailId) {
      await this.markReplied(replyToEmailId);
    }

    return { success: true as const, id: result.emailId, threadId, resendId: result.resendId };
  },

  /**
   * Store mail the webhook received. Returns null for a duplicate delivery.
   * Threading, in order of trust: our plus-address tag, In-Reply-To /
   * References, then subject (Re:) + counterpart address.
   */
  async storeInboundEmail({
    from,
    fromName,
    to,
    subject,
    text,
    html,
    messageId,
    inReplyToHeader,
    referencesHeader,
    threadIdHint,
    resendEmailId,
    cc,
    attachments,
    autoGenerated = false,
  }: {
    from: string;
    fromName?: string | null;
    to: string;
    subject: string;
    text?: string | null;
    html?: string | null;
    /** RFC Message-ID, bare (no angle brackets). */
    messageId?: string | null;
    inReplyToHeader?: string | null;
    referencesHeader?: string | null;
    /** Thread id parsed from our plus-addressed Reply-To (team+<id>@…). */
    threadIdHint?: string | null;
    /** Resend's received-email id (lets us fetch attachments later). */
    resendEmailId?: string | null;
    cc?: string[];
    attachments?: EmailAttachmentMeta[];
    autoGenerated?: boolean;
  }) {
    // Deduplicate: skip if we already stored this message (webhook retry)
    if (resendEmailId) {
      const [existing] = await db
        .select({ id: emails.id })
        .from(emails)
        .where(and(eq(emails.resendId, resendEmailId), eq(emails.direction, 'inbound')))
        .limit(1);
      if (existing) {
        logger.info('inbox', `Duplicate delivery for ${resendEmailId}, skipping`);
        return null;
      }
    }
    if (messageId) {
      const [existing] = await db
        .select({ id: emails.id })
        .from(emails)
        .where(and(eq(emails.direction, 'inbound'), sql`${emails.metadata}->>'messageId' = ${messageId}`))
        .limit(1);
      if (existing) {
        logger.info('inbox', `Duplicate Message-ID ${messageId}, skipping`);
        return null;
      }
    }

    const spam = isLikelySpam({ from, subject, text });

    let threadId: string | null = null;
    let inReplyToId: string | null = null;
    let threadOwnerId: string | null = null;

    const related = async (where: ReturnType<typeof and>) => {
      const [row] = await db
        .select({ id: emails.id, threadId: emails.threadId, userId: emails.userId })
        .from(emails)
        .where(where)
        .orderBy(desc(emails.createdAt))
        .limit(1);
      return row || null;
    };

    // 1. Plus-address tag (team+<threadId>@…) — we set it on every outbound
    //    Reply-To, so this is exact. Verify the thread exists so a guessed or
    //    forged tag can't attach mail to nothing.
    if (!spam && threadIdHint) {
      const latest = await related(inThread(threadIdHint));
      if (latest) {
        threadId = latest.threadId || threadIdHint;
        inReplyToId = latest.id;
        threadOwnerId = latest.userId;
      }
    }

    // 2. In-Reply-To / References → a message we have stored
    if (!spam && !threadId && (inReplyToHeader || referencesHeader)) {
      const headerIds = [inReplyToHeader, referencesHeader]
        .filter(Boolean)
        .join(' ')
        .match(/<([^>]+)>/g)
        ?.map((id) => id.slice(1, -1)) || [];
      if (headerIds.length > 0) {
        const found = await related(
          or(...headerIds.map((hid) => sql`${emails.metadata}->>'messageId' = ${hid}`))!,
        );
        if (found) {
          threadId = found.threadId || found.id;
          inReplyToId = found.id;
          threadOwnerId = found.userId;
        }
      }
    }

    // 3. Last resort: subject (Re: prefix) + counterpart address
    if (!spam && !threadId && subject) {
      const cleanSubject = subject.replace(/^((re|fwd?|aw|sv):\s*)+/i, '').trim();
      if (cleanSubject && cleanSubject !== subject.trim()) {
        const found = await related(
          and(
            ilike(emails.subject, escapeLike(cleanSubject)),
            or(eq(emails.toEmail, from), eq(emails.fromEmail, from)),
          )!,
        );
        if (found) {
          threadId = found.threadId || found.id;
          inReplyToId = found.id;
          threadOwnerId = found.userId;
        }
      }
    }

    if (!threadId) threadId = randomUUID();

    // Link the sender to a client. The From address is sender-controlled, so
    // LIKE wildcards are escaped (a bare `%@%` would match any client).
    const [matchedClient] = await db
      .select({ id: clients.id, userId: clients.userId })
      .from(clients)
      .where(ilike(clients.email, escapeLike(from)))
      .limit(1);

    // Owner: the thread's owner (authoritative), else the matched client's
    // user, else the default admin so unknown senders still show up.
    const ownerUserId = threadOwnerId ?? matchedClient?.userId ?? (await getDefaultOwnerId());

    const meta: EmailMetadata = {};
    if (messageId) meta.messageId = messageId;
    if (cc?.length) meta.cc = cc;
    if (attachments?.length) meta.attachments = attachments;
    if (autoGenerated) meta.autoGenerated = true;
    if (inReplyToHeader || referencesHeader) {
      meta.headers = {
        ...(inReplyToHeader ? { 'In-Reply-To': inReplyToHeader } : {}),
        ...(referencesHeader ? { References: referencesHeader } : {}),
      };
    }

    // onConflictDoNothing backstops the pre-check via the partial unique
    // index on resend_id (a concurrent retry).
    const [stored] = await db
      .insert(emails)
      .values({
        userId: ownerUserId,
        clientId: matchedClient?.id || null,
        direction: 'inbound',
        fromEmail: from,
        fromName: fromName || null,
        toEmail: to,
        cc: cc?.length ? cc.join(', ') : null,
        subject: subject || '(no subject)',
        bodyHtml: html || null,
        bodyText: text || null,
        status: 'received',
        resendId: resendEmailId || null,
        threadId,
        inReplyToId,
        isRead: false,
        isSpam: spam,
        metadata: meta,
      })
      .onConflictDoNothing()
      .returning();

    if (!stored) {
      logger.info('inbox', `Concurrent duplicate for ${resendEmailId}, skipping`);
      return null;
    }

    // The message we sent got an answer.
    if (inReplyToId) {
      await db
        .update(emails)
        .set({ status: 'replied', repliedAt: new Date() })
        .where(and(eq(emails.id, inReplyToId), eq(emails.direction, 'outbound')));
    }

    return stored;
  },

  async markReplied(id: string) {
    await db
      .update(emails)
      .set({ status: 'replied', repliedAt: new Date() })
      .where(eq(emails.id, id));
  },

  async updateDeliveryStatus(resendId: string, status: 'delivered' | 'bounced' | 'failed') {
    // Only outbound rows carry a delivery status; inbound rows also store a
    // Resend id (the received-email id) and must not be touched. Don't
    // regress an email that already received a reply.
    await db
      .update(emails)
      .set({ status })
      .where(and(eq(emails.resendId, resendId), eq(emails.direction, 'outbound'), ne(emails.status, 'replied')));
    await db.update(emailLogs).set({ status }).where(eq(emailLogs.resendId, resendId));
  },

  async getSetting(key: InboxSettingKey): Promise<boolean> {
    const [row] = await db
      .select({ value: platformSettings.value })
      .from(platformSettings)
      .where(eq(platformSettings.key, key))
      .limit(1);
    return row?.value === true;
  },

  async setSetting(key: InboxSettingKey, value: boolean) {
    await db
      .insert(platformSettings)
      .values({ key, value, updatedAt: new Date() })
      .onConflictDoUpdate({
        target: platformSettings.key,
        set: { value, updatedAt: new Date() },
      });
  },

  /** `Boca Banker <team@bocabanker.com>`'s bare address, for the UI. */
  fromAddress: getFromAddress,
};
