#!/usr/bin/env npx tsx
/**
 * Seed all 61 existing reviews for Boca Banker into the reviews table.
 * All reviews are pre-approved since they come from verified sources.
 */

import 'dotenv/config'
import postgres from 'postgres'

const DATABASE_URL = process.env.DATABASE_URL!

if (!DATABASE_URL) {
  console.error('Missing DATABASE_URL')
  process.exit(1)
}

const sql = postgres(DATABASE_URL)

interface SeedReview {
  reviewer_name: string
  reviewer_city: string | null
  reviewer_state: string | null
  rating: number
  title: string
  body: string
  loan_status: string | null
  loan_type: string | null
  interest_rate_experience: string | null
  closed_on_time: boolean | null
  fees_experience: string | null
  loan_term: string | null
  loan_program: string | null
  is_first_time_buyer: boolean | null
  is_self_employed: boolean | null
  status: string
  response_text: string | null
  review_date: string | null
}

const reviews: SeedReview[] = [
  {
    reviewer_name: 'Justin Turner',
    reviewer_city: 'Seminole',
    reviewer_state: 'FL',
    rating: 5,
    title: 'My first home',
    body: 'Boca Banker was outstanding and there every step of the way, very helpful and always sharp and right to the point. I\'m very blessed to have someone like him to have had helped me buy my first home. Super nice, super honest.',
    loan_status: 'Pre-qualified',
    loan_type: 'Conventional',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: '30 year fixed',
    loan_program: 'Refinance',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Justin, thank you so much for your very kind reply...sincerely stated in every way! It was such a pleasure working with you! You were always so quick to respond to every request for Documentation required which allowed the process to move all the more smoothly. I pray you have many wonderful memories in your new home and wish you the very best in your profession!',
    review_date: '2026-01-18',
  },
  {
    reviewer_name: 'Angela Shropshire',
    reviewer_city: 'Bonita Springs',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Best Experience',
    body: 'I have bought a lot of homes and it is usually a stressful experience working with lenders. Working with Boca Banker was different. He was very thorough, always thinking ahead and available anytime I needed him. I felt his knowledge about loan options was very helpful in finding the best fit.',
    loan_status: 'Closed Jun 2025',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: true,
    status: 'approved',
    response_text: 'Thank you for your gracious words, Angela...sincerely appreciated and never taken for granted! It was truly a pleasure assisting Sam and you in this matter. And...I\'ve got to say...I do not believe I\'ve Ever had a client who responded so quickly and proficiently to my every request! Thank you, again, for allowing me this opportunity!',
    review_date: '2025-06-27',
  },
  {
    reviewer_name: 'Sam A.',
    reviewer_city: 'Miami',
    reviewer_state: 'FL',
    rating: 5,
    title: 'First Property Purchase - Highly Recommend',
    body: 'I worked with Boca Banker on my first Home purchase. I honestly didn\'t know what I was doing, I completely went into this without a Realtor, so everything I was doing was on my own. But I was so glad and appreciative of Boca Banker. He walked me through every step.',
    loan_status: 'Closed Apr 2025',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2025-05-15',
  },
  {
    reviewer_name: 'Giovanna Baffuto',
    reviewer_city: 'Lake Worth Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'HIGHLY RECOMMEND!',
    body: 'Boca Banker is the best in the game! We worked together while buying my first home and he walked me through every step. He is incredibly knowledgeable and experienced, always available day or night- I highly recommend Boca Banker and will be contacting him again in the future when buying my next home.',
    loan_status: 'Closed Feb 2024',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: null,
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2024-02-14',
  },
  {
    reviewer_name: 'Pamela Calder',
    reviewer_city: 'Delray Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'The most comforting and helpful part of this process!',
    body: 'Buying a house is so intimidating but buying a house in this economy is terrifying! Boca Banker walked us through the process, step-by-step, and made it almost enjoyable. He was such a key factor in making this work, and helping us find our dream home. We could not be more grateful.',
    loan_status: 'Closed Jan 2024',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2024-02-14',
  },
  {
    reviewer_name: 'Laura and Jonathan K',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Highly Recommend Boca Banker!',
    body: 'Boca Banker went above and beyond when helping us finance our home. He was available whenever we had a question and worked hard to help the process of financing a home go smoothly. He also explained the home buying process to us in detail so we would better understand the process.',
    loan_status: 'Closed May 2023',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2023-05-08',
  },
  {
    reviewer_name: 'Jason Fichter',
    reviewer_city: 'West Palm Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Amazing',
    body: 'Boca Banker made purchasing my new home a breeze! There were some challenges throughout the process but Boca Banker made it his priority to resolve everything and make sure nothing would delay my closing. I feel like I\'ve known Boca Banker for years with how often we spoke. Would absolutely recommend!',
    loan_status: 'Closed May 2023',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2023-05-08',
  },
  {
    reviewer_name: 'Ian P',
    reviewer_city: 'Miami',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Expert Knowledge, Sincere Demeanor, Constant Communication',
    body: 'As a first-time homebuyer, I cannot recommend Boca Banker enough– he was thoughtful, thorough and supported me from start to finish. I was referred to Boca Banker by a good friend and would recommend him to anyone looking to purchase a property. Boca Banker advocated for me and constantly looked for opportunities to help.',
    loan_status: 'Closed May 2023',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2023-05-08',
  },
  {
    reviewer_name: 'Jessica Stephans',
    reviewer_city: 'Darlington',
    reviewer_state: 'SC',
    rating: 5,
    title: 'The nicest person I\'ve ever dealt with.',
    body: 'Boca Banker was both informative, and patient with us as first time buyers. He explained everything, quieted any fears, and made this whole process so much easier than we would have ever imagined.',
    loan_status: 'Closed Sep 2022',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2022-09-25',
  },
  {
    reviewer_name: 'Shelby Morency',
    reviewer_city: 'Palm City',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Best Senior Loan Officer Around!',
    body: 'Mr. Boca Banker was a pleasure to work with from the very start. He has the most wonderful personality and is so thorough - he took great care in making sure everything was handled perfectly. We needed a very quick closing and Boca Banker made it happen in under 20 days!',
    loan_status: 'Closed Apr 2022',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Shelby! Thank you so much for your gracious remarks! It was such a pleasure working with Michael and you...and nothing made me happier than to see your smiling faces in your new home! I pray your new abode will be the location of many wonderful memories--for you and your entire family--in the years ahead! Thank you for allowing me the opportunity to serve you in this important transaction...I never take such for granted.',
    review_date: '2022-05-12',
  },
  {
    reviewer_name: 'Nader Atoui',
    reviewer_city: 'Wellington',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Exceptional isn\'t enough to describe Boca Banker',
    body: 'I am not sure where to start.. and I am not sure my review would even satisfy me in describing the exceptional job Boca Banker did not only for my house, but for my parents as well who bought at the same time. Professional, above and beyond, available around the clock.',
    loan_status: 'Closed Mar 2022',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Nader! Anyone reading your "over-the-top" review will only be sure I paid you for your remarks! LOL What a great time we had working on you and your mom and dad\'s purchases simultaneously! I so appreciate the trust you placed in me during the process--words cannot express, sufficiently, my appreciation for such. Again...thank you for your many, kind words--not one is taken for granted and all met with deepest appreciation.',
    review_date: '2022-03-28',
  },
  {
    reviewer_name: 'Ayana Hart',
    reviewer_city: 'Port Saint Lucie',
    reviewer_state: 'FL',
    rating: 5,
    title: 'THE BEST! THE BEST! THE BEST!',
    body: 'Our experience with Boca Banker was nothing less than professional, top notch, thorough, and excelled beyond our expectations. From the beginning of this process of moving, it was stressful. But Boca Banker made the loan process easy for us. He was so knowledgeable about every detail, and he helped us tremendously.',
    loan_status: 'Closed Nov 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Ayana! I cannot thank you enough for your gracious review! I so enjoyed the opportunity of working with Terence and you!! Such a pleasure working with such an incredible couple. Thank YOU for allowing me the opportunity to assist you in this very important matter. I know that you and your family will make many, wonderful memories in your new home!!',
    review_date: '2022-03-01',
  },
  {
    reviewer_name: 'Terence Hart',
    reviewer_city: 'Port Saint Lucie',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Boca Banker',
    body: 'We had an AMAZING experience with Boca Banker. He is absolutely the best at what he does. He was there from day one. Always staying in touch making sure the process runs smoothly.',
    loan_status: 'Closed Nov 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2022-02-06',
  },
  {
    reviewer_name: 'Erin P.',
    reviewer_city: 'Deerfield Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'First Time Homebuyer Wizard',
    body: 'If you need coaching through the first time homebuying process, Boca Banker is spectacular. We were involved in a private sale as first time homebuyers (no realtor on either side) and his guidance was EVERYTHING! He\'s always looking out to make sure you\'re making a great, long-term decision with your money.',
    loan_status: 'Closed Sep 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: null,
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Erin! I am almost hesitant to have you post this review...someone is going to be sure I paid you to say all you did! LOL Let\'s just say it was a pleasure working with Pastor Jimmy and you. Buying a home IS a Big deal...and I am grateful my input made the process a bit more understandable. I pray this home will hold many wonderful memories for you and your family!',
    review_date: '2021-09-27',
  },
  {
    reviewer_name: 'Cristina Viner',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Spectacular service by Boca Banker!',
    body: 'I am a first time home buyer and Boca Banker made the entire process so easy! He is so knowledgeable and always took time to explain everything. He was always available to answer any questions. I can\'t recommend him enough!! He truly goes above and beyond.',
    loan_status: 'Closed Jul 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you, Cristina, for your gracious reply! Sincerely appreciated in every way. It was such a pleasure getting to know you and your mom during the process. And, as one of PB County\'s finest (in your role as firefighter and EMT), it was a privilege assisting you as well! Thank you for allowing me the opportunity to assist you in this important transaction!',
    review_date: '2021-07-28',
  },
  {
    reviewer_name: 'John Forman',
    reviewer_city: 'Fort Lauderdale',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Best Lender!',
    body: 'This was our first house and Boca Banker has been incredible through the whole process. We started working with Boca Banker back in 2018 and we took a run at purchasing multiple properties and Boca Banker helped us with each one. He was so patient and incredibly responsive and professional.',
    loan_status: 'Closed Jun 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: true,
    status: 'approved',
    response_text: 'John! Thank you for your kind words...sincerely appreciated in every way! It has been such a pleasure working with (and getting to know!) Sarah and you during the process. My prayer is that God will bless you with many, wonderful memories in your new home. Of course, I do look forward to staying in touch!!',
    review_date: '2021-07-26',
  },
  {
    reviewer_name: 'Bongomin Otii',
    reviewer_city: 'Delray Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Fantastic Mortgage Broker',
    body: 'I don\'t have enough platitudes to describe the job Boca Banker did for us in helping us close on our condo. I was recommended to him by a friend who spoke highly of him. From our first phone call until we closed on the condo, Boca Banker was positively engaged throughout the process.',
    loan_status: 'Closed Jul 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Bo and Kacey! Thank you for your overly-kind review! It was so much fun working with the two of you as well as assisting in the financing of your first home purchase. I sincerely appreciate the opportunity you allowed me in this important transaction and trust your new abode will afford you many wonderful memories in the years ahead.',
    review_date: '2021-07-04',
  },
  {
    reviewer_name: 'Rachel P.',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'BEST IN THE MORTGAGE BIZ',
    body: 'Boca Banker is enthusiastic, attentive to detail and extraordinarily caring. He works hard to find the best rate. There are so many different things that come up when getting financing to buy a home and he stays on top of it all. He is friendly, professional and works well with all parties involved.',
    loan_status: 'Closed May 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Rachel and Bill! Thank you for your gracious remarks...they are definitely not taken for granted. Of course, assisting the two of you was more like assisting members of my family...which makes the memory of assisting you all the more important. You know, too, I\'ll be praying that God grants you many wonderful memories, in the years ahead, in your new abode!',
    review_date: '2021-07-02',
  },
  {
    reviewer_name: 'Brian and Sue Steffen',
    reviewer_city: 'Fort Myers Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Helpful and Courteous',
    body: 'Boca Banker helped us through the process of our first loan, and was extremely helpful in explaining our options, answering our questions, keeping track of outstanding items, guiding us on how to obtain and upload the documents that were required. We found ourselves in need of a second loan and went right back to Boca Banker.',
    loan_status: 'Closed Apr 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '15 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Brian and Sue! Thank you so much for your gracious review! It was truly a pleasure working with you but, most importantly, I believe we established a friendship in the process. I really do hope you are enjoying your new condo...and a very sweet one it is!',
    review_date: '2021-06-28',
  },
  {
    reviewer_name: 'Arnie Wasieleski',
    reviewer_city: 'Fort Myers Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Super loan officer',
    body: 'Boca Banker was prompt, professional, and courteous. He was patient and thorough answering all of my questions. He kept the ball rolling and the process was completed in the time frame promised. There were absolutely no surprises at settlement. An excellent job!',
    loan_status: 'Closed May 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: true,
    status: 'approved',
    response_text: 'Arnie! It was such a pleasure working with you! Thank you for your kind remarks--they are not taken lightly and are met with deepest appreciation. I do look forward to introducing my wife, Betsy, to Beverly and you! She has heard all about the Wasieleskis and cannot wait to get together!',
    review_date: '2021-05-02',
  },
  {
    reviewer_name: 'Joey Karram',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'The best in the biz',
    body: 'Boca Banker was the best! My fiancé and I very much enjoyed working with him. Was always available and helped explain the process as we went through it! Would highly recommend for any first time home buyer!',
    loan_status: 'Closed Apr 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you, Joey, for your kind remarks...sincerely appreciated in every way! And, I pray God will continue to bless you in your profession as a Physician Assistant as well as you and your fiancé in your forthcoming marriage! Congratulations on the purchase of your first home and thank you for allowing me the opportunity to be of assistance!',
    review_date: '2021-05-02',
  },
  {
    reviewer_name: 'Diego Eaton',
    reviewer_city: 'Saint Petersburg',
    reviewer_state: 'FL',
    rating: 5,
    title: 'AMAZING- Highly recommend!',
    body: 'Boca Banker is hands down the best mortgage loan officer I have ever worked with. Boca Banker was thorough in every step of the process and made it a point to find the best options and best rates for us. He has the heart of a teacher and will ensure you understand everything.',
    loan_status: 'Closed Feb 2021',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '15 year fixed',
    loan_program: 'Jumbo Loan',
    is_first_time_buyer: true,
    is_self_employed: true,
    status: 'approved',
    response_text: 'Diego! I just realized I failed to reply to your exceedingly-gracious review! Thank you so much for your overly-gracious assessment. You do know it was a pleasure assisting Gina and you...and having the chance to be introduced to the lovely baby Sofia! Please accept Betsy\'s and my best wishes and prayers for you and your family in that lovely new abode! We do look forward to a visit in the near future!',
    review_date: '2021-04-18',
  },
  {
    reviewer_name: 'Amber Rogers',
    reviewer_city: 'West Palm Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Outstanding!!!',
    body: 'I am compelled to write a review about Boca Banker because working with Boca Banker was one of the best experiences I ever had. Boca Banker was the most helpful, informative, thorough, patient and caring person I\'ve ever worked with. His level of professionalism was outstanding. He brought a lot of confidence to the process.',
    loan_status: 'Closed Nov 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you, Amber, for your incredibly kind words. It was a pleasure working with you! I have to say, however, that your assistance in providing--so quickly!--requested documents only allowed the process to move as smoothly as it did. My thanks to Steve and you for allowing me the opportunity to assist you in this very important matter.',
    review_date: '2020-12-07',
  },
  {
    reviewer_name: 'David and Wife',
    reviewer_city: 'Fort Myers',
    reviewer_state: 'FL',
    rating: 5,
    title: 'AMAZING IS AN UNDERSTATEMENT',
    body: 'Boca Banker has made my wife and I change my mind about the myths of how scary it is to purchase a home. We are head over heels happy with Boca Banker\'s professionalism, his love and passion for his job, and his ability to get it done. I will never use another lender.',
    loan_status: 'Closed Nov 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you for your gracious remarks! It was a pleasure working with you and am confident you will have many wonderful memories in your new home. And...thank you for allowing me the opportunity to assist you in this very important matter...sincerely appreciated in every way!',
    review_date: '2020-11-17',
  },
  {
    reviewer_name: 'Bayardo Luna',
    reviewer_city: 'Green Cove Springs',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Beyond Expectations',
    body: 'The way Boca Banker was there every step of the way is the most professional I\'ve ever experienced. He is ahead of the game in every way. He knew every requirement that was needed and so that I was able to in a very timely manner get all documents needed.',
    loan_status: 'Closed Oct 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you, Bayardo, for your very gracious review...your kind words are not taken for granted! Thank YOU for your kindness throughout. It was a pleasure working with you and was thrilled to play a part in helping you and your family realize such a lovely new home!',
    review_date: '2020-10-29',
  },
  {
    reviewer_name: 'Michael',
    reviewer_city: 'Boynton Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Boca Banker',
    body: 'Boca Banker is absolutely phenomenal! He is personable, caring, extremely knowledgeable and dedicated. Boca Banker handles each client as if he is solely working on theirs even if he has multiple clients at a time.',
    loan_status: 'Closed Aug 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Michael, thank you for your kind words...sincerely appreciated and definitely not taken for granted! It was a privilege serving you (as you do each and every day as one of Boca Raton\'s finest!) and getting to know another member of your great family. I know you will have many wonderful and God-blessed memories in your new home!',
    review_date: '2020-09-08',
  },
  {
    reviewer_name: 'Thomas and Jessica M',
    reviewer_city: 'Coconut Creek',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Spectacular Service with a Smile',
    body: 'Boca Banker is who you want working on your home financing! Boca Banker is knowledgeable, communicative, efficient, helpful, authentically himself (he is truly an amazing human being) and works hard to make the home buying process as seamless as possible. This is now our second time working with Boca Banker.',
    loan_status: 'Closed Aug 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you, Jessica, for your overly-gracious words. Sincerely appreciated in every way! It was such a pleasure assisting you (once again!) and having the added benefit of getting to know Thomas! Love your new abode and know it will be a source of many wonderful memories for Thomas and you!',
    review_date: '2020-08-28',
  },
  {
    reviewer_name: 'Julie C.',
    reviewer_city: 'Boynton Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Honest and very helpful',
    body: 'Boca Banker was extremely helpful through the whole process and always communicated with me which was greatly appreciated. I would recommend him to anyone!',
    loan_status: 'Closed Jun 2020',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Julie, it was such a pleasure working with Travis and you! Always love assisting first-time homebuyers!! I trust this finds you already enjoying being in your new home!',
    review_date: '2020-06-30',
  },
  {
    reviewer_name: 'Lisa and Frank',
    reviewer_city: 'Largo',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Boca Banker is an excellent lender',
    body: 'Boca Banker was wonderful to work with. He was very kind and patient with us. He explained everything thoroughly, every step of the way. He is very knowledgeable and answered all of our questions. I highly recommend Boca Banker as your lender!',
    loan_status: 'Closed Jun 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Lisa and Frank! How much fun we had working to nail down financing on your Florida retirement home! It was a pleasure getting to know the two of you and Betsy and I look forward to taking you out for dinner on our next trip to the St Pete area!',
    review_date: '2020-06-17',
  },
  {
    reviewer_name: 'Tayler E',
    reviewer_city: 'Pensacola',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Best of the Best',
    body: 'Boca Banker has been such a blessing. First time home buyer with a husband on deployment, Boca Banker couldn\'t of been a better ray of light more than he was. Always willing to help, explain and answer any questions I had, and just do everything in my best interest. Couldn\'t recommend him enough.',
    loan_status: 'Closed Jun 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'VA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Tayler! It was such a pleasure serving Dustin and you! With Dustin being deployed, you did an extraordinary job handling all the details, while ensuring Dustin was kept fully apprised of each detail as he was aboard the USS Harry S Truman! It is a privilege to serve the military community and, especially, those--like Dustin and you--who are first-time homebuyers!',
    review_date: '2020-06-14',
  },
  {
    reviewer_name: 'Tim King',
    reviewer_city: 'Cape Coral',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Top Notch',
    body: 'I could never have asked for a better loan officer than Boca Banker. He is top notch and right on point. Boca Banker walked me through the whole process with ease. He has a great way communicating and explains everything along the way. Completely smooth process and hassle free.',
    loan_status: 'Closed May 2020',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you for your gracious remarks, Tim! They are met with sincere gratitude. However, I must counter by saying you were an Exceptional client. Your timely (actually, FAST) follow through, on all, only helped ensure a smooth closing at the end. Above all, I am grateful for the friendship which has ensued!',
    review_date: '2020-05-28',
  },
  {
    reviewer_name: 'Anthony Austin',
    reviewer_city: 'Lake Worth Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Perfect Lender',
    body: 'Mr. Boca Banker was an absolute pleasure to work with. My wife and I were new to the home buying experience and we couldn\'t have asked for a better Lender to lead us step by step through each and every process. Boca Banker made himself accessible to us continuously.',
    loan_status: 'Closed Sep 2019',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2019-11-26',
  },
  {
    reviewer_name: 'Refinance Client',
    reviewer_city: 'Cutler Bay',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Refinance',
    body: 'I had a great experience. Everything was made the more easier and he went the extra mile to help explain my options. Many thanks to Boca Banker.',
    loan_status: 'Closed Oct 2019',
    loan_type: 'Refinance',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2019-10-27',
  },
  {
    reviewer_name: 'The Troupes',
    reviewer_city: 'Palm Bay',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Outstanding',
    body: 'Boca Banker was introduced to my husband and I by a close friend. Boca Banker is one in a million. He\'s reliable, efficient, honest and his personality is outstanding. Boca Banker was there for us throughout. You can call him at nights, weekends he\'s always available to answer your calls, texts and emails.',
    loan_status: 'Closed Jul 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-07-25',
  },
  {
    reviewer_name: 'A. Avecillas',
    reviewer_city: 'Miami',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Responsible, Effective and Extremely Knowledgeable',
    body: 'Boca Banker made my first-time home purchase experience a dream! He was ALWAYS available for questions, constant communication throughout the whole process, extremely efficient and works with a sense of urgency. Not only does he have a breadth of knowledge in all things lending-related, I had a sense of comfort from the beginning.',
    loan_status: 'Closed Jun 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-06-22',
  },
  {
    reviewer_name: 'Claudia Militaru',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Boca Banker the BEST!!',
    body: 'Boca Banker is the best! I could not be more grateful to Boca Banker for helping me with my first home. He is incredible and I could not ask for someone better. He is very knowledgeable and experienced. And most importantly he is very patient, kind and encouraging. He never hesitated to help.',
    loan_status: 'Closed Apr 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-06-18',
  },
  {
    reviewer_name: 'Alex & Ashlynn Jones',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Wouldn\'t go with anyone else!',
    body: 'Experienced, responsive, great rate, helpful, and gets it done. We had a tough situation and Boca Banker provided possible options that actually made it a reality for us to be able to get our dream home. We have worked with Boca Banker prior on our first home 5 years ago as new homebuyers.',
    loan_status: 'Closed Jun 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-06-17',
  },
  {
    reviewer_name: 'Andrew Fischer',
    reviewer_city: 'Mastic Beach',
    reviewer_state: 'NY',
    rating: 5,
    title: 'Great!',
    body: 'Moving into a home is not easy in NY but Boca Banker made the process a breeze. Rates were better than any of the competitors I had quotes with too. A+ and highly recommend using Boca Banker for your purchase!',
    loan_status: 'Closed Mar 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-05-23',
  },
  {
    reviewer_name: 'Ryan Scharmann',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'The man the myth the legend',
    body: 'Boca Banker is the man! Available nights, weekends, and everything in between. Makes you feel like you\'re his top priority and has answers to any question you might have. He made the mortgage experience truly enjoyable and I would absolutely recommend him to anyone!',
    loan_status: 'Closed Mar 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '15 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-04-05',
  },
  {
    reviewer_name: 'Matt P',
    reviewer_city: 'Port Saint Lucie',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Professional, intuitive, and hard working',
    body: 'Boca Banker was a pleasure to work with..since Day 1 I knew he would be able to handle everything that comes to a first home purchase. Very professional, and knowledgeable in the field he was able to give me insight that will be valuable for years to come. I would highly recommend him.',
    loan_status: 'Closed Mar 2018',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: true,
    fees_experience: null,
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-04-05',
  },
  {
    reviewer_name: 'Elynn G.',
    reviewer_city: 'North Haven',
    reviewer_state: 'CT',
    rating: 5,
    title: 'Boca Banker is communicative, personable, and he gets the job done!',
    body: 'Boca Banker is absolutely wonderful to work with. Finances aren\'t my strong suit and Boca Banker walked me through everything. I am out of state and Boca Banker was in touch with me via email and phone calls every step of the way, keeping me informed and making sure all of my questions were answered.',
    loan_status: 'Closed Jan 2018',
    loan_type: 'Refinance',
    interest_rate_experience: 'Lower than expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-02-20',
  },
  {
    reviewer_name: 'Renato Paiva',
    reviewer_city: 'West Palm Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'A Loan Officer Who Went Well Beyond My Expectations!',
    body: 'Boca Banker was recommended by the realtor who I worked with when purchasing my first home in Florida. Although I dealt with several loan officers in the past, not one of them communicated and executed the entire process like Boca Banker did, from the first time I spoke with him to the closing.',
    loan_status: 'Closed Jan 2018',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2018-01-15',
  },
  {
    reviewer_name: 'J. Siegfried',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Local Lender provides the personal touch!',
    body: 'My realtor gave me Boca Banker\'s contact information and the rest is history. From the first moment I was in contact with Boca Banker until we closed today, I have been completely up to speed on all aspects of my home loan. He was available at anytime to help.',
    loan_status: 'Closed Oct 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-10-24',
  },
  {
    reviewer_name: 'Alexander Karram',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Fantastic experience!',
    body: 'Boca Banker was incredibly knowledgeable and helpful! He fully explained the whole processes and told us what to expect. I\'d recommend Boca Banker in a heartbeat!',
    loan_status: 'Closed Nov 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-11-04',
  },
  {
    reviewer_name: 'Olinia Arce',
    reviewer_city: 'Lake Worth Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Amiable Devoted Warmhearted Professional',
    body: 'It was an absolute pleasure working with this knowledgeable man! The house hunting took over two years and not once did he show frustration but rather continuous dedication and patience. Boca Banker is an amiable devoted warmhearted professional that proved my skeptic eye wrong!',
    loan_status: 'Closed Sep 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-09-30',
  },
  {
    reviewer_name: 'Erik',
    reviewer_city: 'West Palm Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Highly Recommended',
    body: 'Boca Banker was an absolute pleasure to work with from beginning to end. He is kind, professional, available, prompt, and honest. I had many questions for Boca Banker throughout our process. I asked them in various forms (text, email, phone) and not always within business hours. Boca Banker was always quick to respond.',
    loan_status: 'Closed Jun 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: '30 year fixed',
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: 'Thank you so much, Erik, for your kind and generous remarks. It was truly a pleasure working with you and trust your new home brings many, joy-filled memories for Hannah and you!',
    review_date: '2017-06-24',
  },
  {
    reviewer_name: 'Logan Poirier',
    reviewer_city: 'Boca Raton',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Incredible!!',
    body: 'Boca Banker was the greatest loan officer. I had begun the process of buying a home with a different loan officer, however I\'m incredibly grateful for the situation that brought me to Boca Banker. He was always available to talk and answer any questions. He explained the home buying process in great detail.',
    loan_status: 'Closed Apr 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'Lower than expected',
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-05-17',
  },
  {
    reviewer_name: 'Jason Leith',
    reviewer_city: 'Rancho Santa Margarita',
    reviewer_state: 'CA',
    rating: 5,
    title: 'Boca Banker helped with all my questions and more!',
    body: 'I had an hour-long phone call with Boca Banker so that he could share with me some basics about home buying and I am walking away feeling much more confident about taking the next steps. He opened my horizons to new possibilities and his first time buyer PDF helped me a lot.',
    loan_status: 'In progress',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: '30 year fixed',
    loan_program: 'FHA Loan',
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-05-15',
  },
  {
    reviewer_name: 'Brian Keith Miles',
    reviewer_city: 'Fort Lauderdale',
    reviewer_state: 'FL',
    rating: 5,
    title: 'HIGHLY RECOMMEND!!!',
    body: 'BOCA BANKER IS EXCELLENT IN HIS PROFESSION. HE\'S PRECISE AND HEARTFELT AT THE SAME TIME. HE MADE OUR PROCESS FEEL LIKE A BLESSING! THANKS BOCA BANKER.',
    loan_status: 'Closed May 2017',
    loan_type: 'Purchase',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: true,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-05-12',
  },
  {
    reviewer_name: 'Former Client',
    reviewer_city: 'Lake Worth Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Excellent',
    body: 'Working with Boca Banker was truly a pleasure. He was extremely reliable and willing to take a call at any time. I had an issue with missing tax paperwork and he even called the IRS to figure out the easiest way to get in touch with the correct representative. He went above and beyond.',
    loan_status: 'Closed Dec 2016',
    loan_type: 'Refinance',
    interest_rate_experience: 'As expected',
    closed_on_time: true,
    fees_experience: 'As expected',
    loan_term: null,
    loan_program: 'Conventional Loan',
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2017-04-19',
  },
  {
    reviewer_name: 'Alexandra Speranza',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'An angel sent by God!',
    body: 'We could describe Boca Banker as an angel sent by God! We found him at the most desperate time when we were only 3 weeks away to the closing of our current home and yet did not have a loan for a new house. He answered our first call on a Saturday and worked tirelessly.',
    loan_status: 'Closed Jun 2016',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2016-06-06',
  },
  {
    reviewer_name: 'Albee N.',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Boca Banker came to us - the best!',
    body: 'Boca Banker is the best! For a seamless mortgage process he\'s the guy! He\'s always available to answer questions and handle all issues that may arise. Boca Banker came to us we did not have to travel to his office. He has no problems providing his personal cell number.',
    loan_status: 'Closed Apr 2016',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2016-04-29',
  },
  {
    reviewer_name: 'Potter M.',
    reviewer_city: 'Vero Beach',
    reviewer_state: 'FL',
    rating: 5,
    title: 'He was kind and respectful no matter how simple the question.',
    body: 'Boca Banker was very helpful in explaining the process and giving us all the information we asked for as we acquired our home loan. He was available by phone, email and text day or night if we needed him. He was kind and respectful no matter how simple the question.',
    loan_status: 'Closed Apr 2016',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2016-04-19',
  },
  {
    reviewer_name: 'Henry',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'I can\'t say enough!!!! What a pleasure it was.',
    body: 'If you want someone who returns your calls immediately, has the answers to your questions, and walks you through the process step by step, BOCA BANKER is the person. I can\'t say enough!!!! What a pleasure it was. Thank you BOCA BANKER!!!!',
    loan_status: 'Closed Jan 2016',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2016-01-18',
  },
  {
    reviewer_name: 'Erickson',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'It impressed me to how extremely personal he was.',
    body: 'I have never met a man so very dedicated to his service. It impressed me to how extremely personal he was. I sometimes felt this gentleman worked 24/7 that truly explains how work motivated this man was. I felt I knew him personally. He was my poster banker.',
    loan_status: 'Closed Jan 2016',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2016-01-11',
  },
  {
    reviewer_name: 'A. Cangialos',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'He was always available to answer questions or to update the timeline.',
    body: 'My husband and I found the house of our dreams and now we needed a mortgage. Enter Boca Banker. Boca Banker was wonderful. Not only did he find us a very good rate, he held our hand through the entire process. He was always available to answer questions or to update the timeline.',
    loan_status: 'Closed May 2015',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2015-05-27',
  },
  {
    reviewer_name: 'Stephen Brecher',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'He truly cares about his clients.',
    body: 'If you want personal service with a professional touch Boca Banker is the guy you go to. Everything regarding our closing was painless. I can\'t even express my gratitude for Boca Banker\'s professional expertise. He truly cares about his clients.',
    loan_status: 'Closed May 2015',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2015-05-13',
  },
  {
    reviewer_name: 'J.R. Gees',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'Extremely knowledgeable and professional',
    body: 'Boca Banker was fabulous to work with. He is extremely knowledgeable and professional while at the same time being very personable and friendly. He always kept us abreast of the process step by step on a daily basis and was able to and encouraged any questions that we had.',
    loan_status: 'Closed Feb 2015',
    loan_type: 'Refinance',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2015-02-24',
  },
  {
    reviewer_name: 'In The Ocean',
    reviewer_city: 'Fort Lauderdale',
    reviewer_state: 'FL',
    rating: 5,
    title: 'He always went well out of his way to ensure I was taken care of',
    body: 'Due to my employment and living circumstances there were many obstacles and hoops that Boca Banker had to jump through to make my refinance complete and successful. He always went well out of his way to ensure that I was taken care of and able to fulfill the requirements of the lender.',
    loan_status: 'Closed Jan 2015',
    loan_type: 'Refinance',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2015-01-26',
  },
  {
    reviewer_name: 'Cara Naland',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'We encountered some problems which he handled with ease.',
    body: 'I strongly recommend Boca Banker for home financing needs. He was spot on with his advice, responsive to my questions and a true professional in his field. We had our own plan of action and Boca Banker suggested other possible ways of financing the loan, one of which we had not thought of.',
    loan_status: 'Closed Apr 2014',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2014-04-10',
  },
  {
    reviewer_name: 'Sebastian Homebuyer',
    reviewer_city: 'Sebastian',
    reviewer_state: 'FL',
    rating: 5,
    title: 'He helped us through the entire process of buying our home.',
    body: 'Boca Banker is simply the best. He helped us through the entire process of buying our home. We were in contact regularly and he kept us up on the progress of our loan. We highly recommend him!',
    loan_status: 'Closed Apr 2014',
    loan_type: 'Purchase',
    interest_rate_experience: null,
    closed_on_time: null,
    fees_experience: null,
    loan_term: null,
    loan_program: null,
    is_first_time_buyer: false,
    is_self_employed: false,
    status: 'approved',
    response_text: null,
    review_date: '2014-04-19',
  },
]

async function main() {
  console.log(`Seeding ${reviews.length} reviews...\n`)

  // Check if already seeded
  const existing = await sql`SELECT count(*) FROM reviews`
  if (Number(existing[0].count) > 0) {
    console.log(`Already have ${existing[0].count} reviews in DB. Skipping seed.`)
    await sql.end()
    return
  }

  for (const r of reviews) {
    await sql`
      INSERT INTO reviews (
        reviewer_name, reviewer_city, reviewer_state, rating, title, body,
        loan_status, loan_type, interest_rate_experience, closed_on_time,
        fees_experience, loan_term, loan_program, is_first_time_buyer,
        is_self_employed, status, response_text, review_date
      ) VALUES (
        ${r.reviewer_name}, ${r.reviewer_city}, ${r.reviewer_state}, ${r.rating},
        ${r.title}, ${r.body}, ${r.loan_status}, ${r.loan_type},
        ${r.interest_rate_experience}, ${r.closed_on_time}, ${r.fees_experience},
        ${r.loan_term}, ${r.loan_program}, ${r.is_first_time_buyer},
        ${r.is_self_employed}, ${r.status}, ${r.response_text}, ${r.review_date}
      )
    `
  }

  const count = await sql`SELECT count(*) FROM reviews`
  console.log(`Successfully seeded ${count[0].count} reviews.`)
  await sql.end()
}

main().catch(console.error)
